# Generated by Django 5.2.11 on 2026-10-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='api_key',
        ),
    ]
