# Generated by Django 5.2.11 on 2026-10-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_api_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
