# Generated by Django 5.2.11 on 2026-10-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='tokens',
        ),
    ]
